version: "2"

linters:
  # The value can be: `standard`, `all`, `none`, or `fast`.
  default: all
  disable:
    - gomoddirectives
    - intrange
    - copyloopvar
    - err113
    - paralleltest
    - nlreturn
    - wsl
    - godot
    - dupl
    - mnd
    - nonamedreturns
    - testpackage
    - cyclop
    - funlen
    - gochecknoglobals
    - tagliatelle
    - nakedret
    - exhaustruct
    - tagalign
    - varnamelen
    - nestif
    - lll
    - gosmopolitan
    - gocognit
    - maintidx
    - zerologlint
    - recvcheck
  settings:
    depguard:
      rules:
        main:
          # - `original`: allowed if it doesn't match the deny list and either matches the allow list or the allow list is empty.
          # - `strict`: allowed only if it matches the allow list and either doesn't match the deny list or the allow rule is more specific (longer) than the deny rule.
          # - `lax`: allowed if it doesn't match the deny list or the allow rule is more specific (longer) than the deny rule.
          # Default: "original"
          list-mode: lax
          # 不允许的依赖包列表
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
  exclusions:
    # Default: lax
    generated: lax
    # Log a warning if an exclusion rule is unused.
    # Default: false
    warn-unused: false
    # Predefined exclusion rules.
    # Default: []
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    paths:
      - vendor
      - .idea
      - .vscode
      - bin
      - output
    rules:
      # 设置某个目录的排除规则
      - path: _test\.go
        linters:
          - depguard
#      - linters:
#          - depguard
#        text: "is not allowed from list 'Main'"
      - linters:
          - gocritic
        text: "unnecessaryDefer:"
      - linters:
          - gocyclo
        text: "is high"
      - linters:
          - wrapcheck
        text: "error returned from external package is unwrapped"
      - linters:
          - gosec
        text: "G401"
      - linters:
          - gosec
        text: "G501"

# Output configuration options.
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true

  # Default: ""
  path-prefix: ""

  sort-order:
    - linter
    - severity
    - file # filepath, line, and column.
  show-stats: false


run:
  timeout: 5m
  relative-path-mode: gomod
  tests: false
  # Allowed values: readonly|vendor|mod
  modules-download-mode: mod
  allow-parallel-runners: true
  allow-serial-runners: true
  concurrency: 0

severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
